services:
    start_hack_postgresql_db:
        image: postgis/postgis:17-3.5
        labels:
            org.springframework.boot.service-connection: postgres  # this is needed since spring does not recognize postgis
        environment:
            POSTGRES_PASSWORD: start_hack
            POSTGRES_DB: start_hack
            POSTGRES_USER: start_hack
        ports:
            - "5432:5432"
        volumes:
            - start_hack_postgresql_db_data:/var/lib/postgresql/data
volumes:
    start_hack_postgresql_db_data:
