ch.sthomas.hack.start.service.admin.folder=/data/Admin_layers
ch.sthomas.hack.start.public.folder=/public
ch.sthomas.hack.start.service.modis-lct.folder=/data/Modis_Land_Cover_Data
ch.sthomas.hack.start.service.modis-gp.folder=/data/MODIS_Gross_Primary_Production_GPP
ch.sthomas.hack.start.service.population-density.folder=/data/Gridded_Population_Density_Data
ch.sthomas.hack.start.service.data.folder=/data
ch.sthomas.hack.start.service.climate-precipitation.folder=/data/Climate_Precipitation_Data

